In [3]:
import csv, sqlite3
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style='darkgrid')

# load/read data from data.csv into pandas dataframe 
df = pd.read_csv('alldata.csv', encoding='utf-8', low_memory=False)
df # print out data to verify it's there

,order_number,ordered_item_style,ordered_item_pattern,ordered_item_size,total,shipto_person_name,shipto_person_city,shipto_person_state_code,shipto_person_state_name,shipto_person_country_code,shipto_person_postal_code,coupon_code
0,49,LEGGINGS_ONE_SIZE,AMERICANA,ONE SIZE,30,Barbar Hoel,Cincinnati,OH,Ohio,US,45230,NaN
1,49,LEGGINGS_ONE_SIZE,AMERICANA,ONE SIZE,30,Barbar Hoel,Cincinnati,OH,Ohio,US,45230,NaN
2,50,LEGGINGS _KIDS_ LXL,AMERICANA,LARGE KIDS,24,Barbar Hoel,Cincinnati,OH,Ohio,US,45230,BACK2SCHOOL
3,50,LEGGINGS _KIDS_ SMALL,AMERICANA,SMALL KIDS,24,Barbar Hoel,Cincinnati,OH,Ohio,US,45230,BACK2SCHOOL
4,72,LEGGINGS_ONE_SIZE,AMERICANA,ONE SIZE,30,Guadalupe Perez,Sun Valley,CA,California,US,91352,NaN
5,72,LEGGINGS_ONE_SIZE,AMERICANA,ONE SIZE,30,Guadalupe Perez,Sun Valley,CA,California,US,91352,SPRINGFREE
6,114,LEGGINGS_ONE_SIZE,AMERICANA,ONE SIZE,30,Lynsey Herlihy,Arroyo Grande,CA,California,US,93420,NaN
7,121,LEGGINGS_ONE_SIZE,AMERICANA,ONE SIZE,25,Brent Reynolds,Bassett,VA,Virginia,US,24055,BACK2SCHOOL
8,145,LEGGINGS_TALL_CURVY,AMERICANA,TALL CURVY,25,Vikki Lansing Copley,Sioux Falls,SD,South Dakota,US,57105,BACK2SCHOOL
9,155,LEGGINGS_TALL_CURVY,AMERICANA,TALL CURVY,25,Marlena Kaanehe,Mililani,HI,Hawaii,US,96789,NaN
10,165,LEGGINGS _KIDS_ LXL,AMERICANA,LARGE KIDS,24,Shannon Allen,Yorba Linda,CA,California,US,92886,NaN
11,176,LEGGINGS _KIDS_ LXL,AMERICANA,LARGE KIDS,23,marlene waite,watertown,NY,New York,US,13601,NaN
12,185,LEGGINGS_ONE_SIZE,AMERICANA,ONE SIZE,30,ELIZABETH A GREENE,CHEEKTOWAGA,NY,New York,US,14225,NaN
13,185,LEGGINGS_ONE_SIZE,AMERICANA,ONE SIZE,30,ELIZABETH A GREENE,CHEEKTOWAGA,NY,New York,US,14225,NaN
14,198,LEGGINGS_TALL_CURVY,AMERICANA,TALL CURVY,25,Jean Weiss,Stillwater,MN,Minnesota,US,55082,LETSGOROE
15,206,LEGGINGS_TALL_CURVY,AMERICANA,TALL CURVY,25,Vicki Godsey,Kingsport,TN,Tennessee,US,37660,NaN
16,213,LEGGINGS_TALL_CURVY,AMERICANA,TALL CURVY,25,Erin Schultz,Fairfax,VA,Virginia,US,22033,NaN
17,214,LEGGINGS_ONE_SIZE,AMERICANA,ONE SIZE,30,Carolyn Meyer,Loveland,CO,Colorado,US,80538,NaN
18,217,LEGGINGS _KIDS_ LXL,AMERICANA,LARGE KIDS,24,Lora haws,Coarsegold,CA,California,US,93614,NaN
19,220,LEGGINGS_TALL_CURVY,AMERICANA,TALL CURVY,25,MaryJo Davis,Alexander,NC,North Carolina,US,28701,NaN
20,222,LEGGINGS_ONE_SIZE,AMERICANA,ONE SIZE,25,alexandra huber,lenox,MA,Massachusetts,US,1240,NaN
21,222,LEGGINGS_ONE_SIZE,AMERICANA,ONE SIZE,25,alexandra huber,lenox,MA,Massachusetts,US,1240,NaN
22,226,LEGGINGS_TALL_CURVY,AMERICANA,TALL CURVY,25,Diane Kimball,Hudson,MA,Massachusetts,US,1749,NaN
23,246,LEGGINGS_TALL_CURVY,AMERICANA,TALL CURVY,25,Michelle McCord,Raymore,MO,Missouri,US,64083,NaN
24,246,LEGGINGS_TALL_CURVY,AMERICANA,TALL CURVY,25,Michelle McCord,Raymore,MO,Missouri,US,64083,NaN
25,249,LEGGINGS_ONE_SIZE,AMERICANA,ONE SIZE,25,Sherri Gagnon,Efland,NC,North Carolina,US,27243,NaN
26,254,LEGGINGS_ONE_SIZE,AMERICANA,ONE SIZE,25,Gayle Cutter,Byfield,MA,Massachusetts,US,1922,NaN
27,258,LEGGINGS_TALL_CURVY,AMERICANA,TALL CURVY,25,Kim Randinelli,Auburn,IN,Indiana,US,46706,NaN
28,259,LEGGINGS_TALL_CURVY,AMERICANA,TALL CURVY,25,Anne Kisner,Poplar Bluff,MO,Missouri,US,63901,NaN
29,284,LEGGINGS_TALL_CURVY,AMERICANA,TALL CURVY,25,Penny T Ward,Saint Michaels,MD,Maryland,US,21663,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
924,261,LEGGINGS_TALL_CURVY,XMAS,TALL CURVY,25,Wanda Solivan,Greenwich,CT,Connecticut,US,6830,NaN
925,266,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,PATRICIA E STREICH,East Greenwich,RI,Rhode Island,US,2818,NaN
926,274,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Pamela K Wehrman,Saint John,IN,Indiana,US,46373,NaN
927,280,LEGGINGS _KIDS_ SMALL,XMAS,SMALL KIDS,23,Stacey Lavender,Chesterfield,NJ,New Jersey,US,8515,NaN
928,291,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Margie,Ronkonkoma,NY,New York,US,11779,NaN
929,300,LEGGINGS_TWEEN,XMAS,TWEEN,23,Delaine Jacobson,Graettinger,IA,Iowa,US,51342,LETSGOROE
930,302,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Stephen Harrell,Quinton,VA,Virginia,US,23141,NaN
931,320,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Christopher Dodge,Topeka,KS,Kansas,US,66614,NaN
932,331,LEGGINGS_TALL_CURVY,XMAS,TALL CURVY,25,Marcella Jones,Birmingham,AL,Alabama,US,35242,NaN
933,336,LEGGINGS _KIDS_ SMALL,XMAS,SMALL KIDS,23,Tracy L Kloos,Williamsport,MD,Maryland,US,21795,NaN
934,342,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Laura De Rosa,El Cajon,CA,California,US,92021,NaN
935,359,LEGGINGS_TC_TWO,XMAS,TCTWO,25,Deborah SCHAEFFER,Navarre,FL,Florida,US,32566-8585,NaN
936,365,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Garod Cavanaugh,Greenwood,IN,Indiana,US,46142,NaN
937,386,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Christine Willis,Atlantic Beach,FL,Florida,US,32233,NaN
938,391,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Shawn Mayberry,Midlothian,VA,Virginia,US,23112,HOLIDAY5FREE
939,391,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Shawn Mayberry,Midlothian,VA,Virginia,US,23112,NaN
940,391,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Shawn Mayberry,Midlothian,VA,Virginia,US,23112,NaN
941,391,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Shawn Mayberry,Midlothian,VA,Virginia,US,23112,NaN
942,391,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Shawn Mayberry,Midlothian,VA,Virginia,US,23112,NaN
943,402,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Kathy Jones,Vacaville,CA,California,US,95696,NaN
944,417,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Pamela Miller,Hudson,IN,Indiana,US,46747-9726,NaN
945,422,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Abby Skerl,Morrison,CO,Colorado,US,80465,NaN
946,450,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Danielle,Anchorage,AK,Alaska,US,99517,HOLIDAY5FREE
947,450,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Danielle,Anchorage,AK,Alaska,US,99517,NaN
948,450,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Danielle,Anchorage,AK,Alaska,US,99517,NaN
949,452,LEGGINGS_ONE_SIZE,XMAS,ONE SIZE,25,Olivia Martinez,Pittsburg,CA,California,US,94565,NaN
950,460,LEGGINGS_TALL_CURVY,XMAS,TALL CURVY,25,Joey Solosky,Winchester,VA,Virginia,US,22603,NaN
951,478,LEGGINGS_TALL_CURVY,XMAS,TALL CURVY,25,Annette Saiz,Bloomfield,NM,New Mexico,US,87413,LETSGOROE
952,519,LEGGINGS_TALL_CURVY,XMAS,TALL CURVY,25,Claudette E Dones,Rochester,NY,New York,US,14621,NaN
953,544,LEGGINGS_TALL_CURVY,XMAS,TALL CURVY,25,CYNTHIA Hargis,Catonsville,MD,Maryland,US,21228,NaN

In [4]:
# make connection to sqlite database and create new db or replace if exists
conn = sqlite3.connect('all_sales.db')

# creates sql table
df.to_sql('all_sales_table', conn, if_exists='replace')

# view chosen columns and alias from table and organize by description
df_all_sales = pd.read_sql_query('SELECT ordered_item_style AS Description, ordered_item_pattern AS Pattern, coupon_code AS Coupon FROM all_sales_table ORDER BY ordered_item_style', conn)
df_all_sales

         Description Pattern        Coupon
0         ANA_MEDIUM    None          None
1         ANA_MEDIUM    None          None
2          ANA_SMALL    None          None
3        AZURE_LARGE    None  HOLIDAY5FREE
4        CARLY_LARGE    None    SPRINGFREE
5        CARLY_LARGE    None          None
6        CARLY_LARGE    None   BACK2SCHOOL
7        CARLY_LARGE    None          None
8        CARLY_LARGE    None    SPRINGFREE
9        CARLY_LARGE    None          None
10       CARLY_LARGE    None          None
11       CARLY_LARGE    None          None
12      CARLY_MEDIUM    None          None
13      CARLY_MEDIUM    None          None
14      CARLY_MEDIUM    None   BACK2SCHOOL
15      CARLY_MEDIUM    None          None
16      CARLY_MEDIUM    None          None
17      CARLY_MEDIUM    None          None
18       CARLY_SMALL    None          None
19       CARLY_SMALL    None          None
20       CARLY_SMALL    None          None
21       CARLY_SMALL    None          None
22       CARLY_SMALL    None          None
23       CARLY_SMALL    None          None
24       CARLY_SMALL    None          None
25       CARLY_SMALL    None          None
26       CARLY_SMALL    None          None
27       CARLY_SMALL    None          None
28       CARLY_SMALL    None          None
29     CARLY_X-LARGE    None          None
..               ...     ...           ...
924    LINDSAY_LARGE    None          None
925    LINDSAY_SMALL    None          None
926       MAXI_SMALL    None          None
927     MAXI_X-LARGE    None          None
928     MAXI_X-SMALL    None          None
929     NICOLE_LARGE    None          None
930     NICOLE_SMALL    None          None
931    PERFECT_LARGE    None          None
932    PERFECT_LARGE    None          None
933    PERFECT_LARGE    None     LETSGOROE
934   PERFECT_MEDIUM    None   BACK2SCHOOL
935   PERFECT_MEDIUM    None          None
936   PERFECT_MEDIUM    None          None
937    PERFECT_SMALL    None          None
938    PERFECT_SMALL    None          None
939  PERFECT_X-LARGE    None          None
940      RANDY_LARGE    None          None
941      RANDY_LARGE    None          None
942      RANDY_LARGE    None          None
943      RANDY_LARGE    None          None
944     RANDY_MEDIUM    None   BACK2SCHOOL
945     RANDY_MEDIUM    None   BACK2SCHOOL
946     RANDY_MEDIUM    None          None
947      RANDY_SMALL    None          None
948      RANDY_SMALL    None          None
949    RANDY_X-LARGE    None          None
950    RANDY_X-SMALL    None     LETSGOROE
951    RANDY_X-SMALL    None          None
952      SARAH_LARGE    None    SPRINGFREE
953    SARAH_X-LARGE    None          None

[954 rows x 3 columns]

In [1]:
# new data set to count concatenated description (concat: collection || print_pattern)
df_pattern_sales = pd.read_sql_query('SELECT ordered_item_style AS Collection, ordered_item_pattern AS Print_Pattern, COUNT(*) AS Items_Sold, ordered_item_style || "_" || ordered_item_pattern AS Desc FROM all_sales_table GROUP BY ordered_item_style, ordered_item_pattern ORDER BY Items_Sold DESC', conn)
df_pattern_sales

NameError: name 'pd' is not defined

In [2]:
# creates plots
f, ax = plt.subplots(figsize=(10,20))

# bar chart
sns.barplot(x='Collection', y='Description', data=df_pattern_sales, color='m', label='Total Sales by Each Size and Pattern')

# label the indexes
ax.set_xlabel('Total Items Sold')
ax.xaxis.set_label_position('top') 
ax.set_ylabel('Style-Size-Pattern') 
ax.xaxis.tick_top()
ax.legend(loc='center right')
plt.show()

NameError: name 'plt' is not defined